base:
  url: https://api-dev.medvantxos.com/api/v1.0
  iurl: https://api-dev.medvantxos.com/iapi/v1.0

site: nebcin
tenant: medvantx

credentials:
  patient:
    username : marklous643@gmail.com
    password : Test@123!

  tenant_admin:
    username: tenant_admin@pfizer.com
    password: Test@123!

  superuser:
    username: default-superuser@medvantx.com
    password: devAdminEw11o##@

drug:
  ndc_rxrequest: '00002050101'
  ndc_rxtransfer: '00002064002'

md_name: 'MARK GROSSMAN'
json_path: '/Users/amit/PycharmProjects/Medic/test_data/'