base:
  url: https://<api_domain>/api/v1.0
  iurl: https://<api_domain>/iapi/v1.0

site: site1
tenant: tenant1

credentials:
  patient:
    username : <user1>
    password : <password1>

  tenant_admin:
    username: <user2>
    password: <password2>

  superuser:
    username: <superuser>
    password: <superpassword>

drug:
  ndc_rxrequest: '00002050101'
  ndc_rxtransfer: '00002064002'

md_name: 'MARK GROSSMAN'
json_path: '/Users/amit/PycharmProjects/Medic/test_data/'
