base_url: https://api-dev.medvantxos.com/api/v1.0
ibase_url: https://api-dev.medvantxos.com/iapi/v1.0
domain: nebcin
tenant: medvantx
superuser: default-superuser@medvantx.com
superuser_password: devAdminEw11o##@"
user: marklous643@gmail.com
password: Test@123!
drug_ndc_rxrequest: '00002050101'
drug_ndc_rxtransfer: '00002064002'
md_name: 'MARK GROSSMAN'
json_path: '/Users/amit/PycharmProjects/Medic/test_data/'