base_url: https://api-sandbox.medvantxos.com/api/v1.0
ibase_url: https://api-sandbox.medvantxos.com/iapi/v1.0
domain: qsymiaxQA
tenant: medvantx
superuser: default-superuser@medvantx.com
superuser_password: saadmin##O554
user: ErSonal@medvantx.com
password: test1234
drug_ndc_rxrequest: '62541020130'
drug_ndc_rxtransfer: '6254120316'
md_name: 'ANGELA SMITH'
json_path: '/Users/amit/PycharmProjects/Medic/test_data/'
