base:
  api_url: https://<api_url>

site: site1
tenant: tenant1

credentials:
  patient:
    username : <user1>
    password : <password1>

  tenant_admin:
    username: <tenant_admin1>
    password: <password1>

  superuser:
    username: <superuser>
    password: <superpassword>

drug:
  ndc : '00023361606'
  ndc_rxrequest: '00002050101'
  ndc_rxtransfer: '00002064002'

md_name: 'MARK GROSSMAN'
json_path: '/Users/amit/PycharmProjects/Medic/test_data/'
